#!/usr/bin/env node
// Renders the site from the repository itself: the catalog, every plugin manifest, and every
// SKILL.md frontmatter. Nothing about a plugin or a skill is retyped in site/, so adding
// either updates the pages with no edit to this script or to a template.
//
// Output: index.html for the catalog, <plugin>/index.html for each catalogued plugin,
// mcp/index.html for the server a plugin owns, and two machine-readable indexes of those
// same pages — sitemap.xml and llms.txt.
//
// Usage: node scripts/build-site.mjs [outDir]          (default outDir: _site)
//        node scripts/build-site.mjs --clean [outDir]  (remove a marked build only)
// Zero dependencies; Node 18+.

import { readFile, readdir, mkdir, writeFile, copyFile, rm } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { join, dirname, basename, resolve, relative, isAbsolute, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SITE = join(ROOT, 'site')
const PARTIALS = join(SITE, 'partials')
const BUILD_MARKER = '.msu-skills-site-build'
const BUILD_MARKER_CONTENT = 'Generated by scripts/build-site.mjs; safe to replace.\n'
// What this site is, in the words every page title ends with. One string, so a plugin page
// and the catalog page cannot describe the site differently.
const SITE_IDENTITY = 'Agent Skills for MapleStory Universe'
// The same role SITE_IDENTITY plays, for the page about the MCP server: one string, so the
// title, the heading, and the llms.txt note cannot describe that server differently.
const MCP_PAGE_IDENTITY = 'MapleStory Universe resource tools'
// Where that page is written. Plugin pages render to /<plugin>/, so a plugin claiming this
// name would collide with it — build() refuses rather than letting one overwrite the other.
const MCP_PAGE_DIR = 'mcp'
// A note in llms.txt is one line in a list, so a description is cut to its first sentence
// and then to this many characters at a word boundary.
const NOTE_LIMIT = 200

const args = process.argv.slice(2)
const cleanOnly = args[0] === '--clean'
const expectedArgs = cleanOnly ? 2 : 1
if (args.length > expectedArgs) {
  throw new Error('usage: node scripts/build-site.mjs [--clean] [outDir]')
}
// resolve, not join: CI passes an absolute path outside the checkout.
const OUT = resolve(ROOT, (cleanOnly ? args[1] : args[0]) ?? '_site')

const ESCAPES = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }
const escape = value => String(value).replace(/[&<>"']/g, char => ESCAPES[char])

const plural = (count, noun) => (count === 1 ? `one ${noun}` : `${count} ${noun}s`)

/** The first sentence of a description, shortened at a word boundary. An llms.txt note is one
 *  line of a list, while a frontmatter description is written for skill matching and runs
 *  several times longer. */
const shortNote = text => {
  const [sentence] = String(text).trim().split(/(?<=\.)\s+(?=[A-Z])/)
  if (sentence.length <= NOTE_LIMIT) return sentence
  const cut = sentence.slice(0, NOTE_LIMIT)
  return `${cut.slice(0, cut.lastIndexOf(' ')).replace(/[,;:—-]$/, '')}…`
}

const readJson = async path => {
  try {
    return JSON.parse(await readFile(path, 'utf8'))
  } catch (error) {
    throw new Error(`cannot read ${path}: ${error.message}`)
  }
}

const listDirs = async path =>
  (await readdir(path, { withFileTypes: true }))
    .filter(entry => entry.isDirectory())
    .map(entry => entry.name)
    .sort()

const userConfigReference = headers =>
  Object.values(headers ?? {})
    .map(value => String(value).match(/^\$\{user_config\.([A-Za-z0-9_-]+)\}$/)?.[1])
    .find(Boolean)

const listFiles = async dir => {
  const entries = await readdir(dir, { withFileTypes: true })
  const nested = await Promise.all(
    entries.map(entry => {
      const path = join(dir, entry.name)
      return entry.isDirectory() ? listFiles(path) : Promise.resolve([path])
    })
  )
  return nested.flat()
}

/** The tools a server exposes, read from the table a skill already keeps for its own agent:
 *  a `## MCP Tool: <server>` heading followed by rows whose first cell is a `code`-quoted
 *  tool name. `.mcp.json` declares how to reach a server, never what it answers, so this
 *  table is the only source — and retyping a tool name into a template would let the page
 *  claim a tool the skills no longer call. */
const parseToolTable = (text, serverName) => {
  const start = text.search(new RegExp(`^##+\\s+MCP Tool:\\s*${serverName}\\s*$`, 'm'))
  if (start === -1) return []

  const [section] = text.slice(start).split(/\n##+\s/)
  return section
    .split('\n')
    .map(line => line.trim())
    .filter(line => line.startsWith('|') && line.endsWith('|'))
    .map(line =>
      line
        .slice(1, -1)
        .split('|')
        .map(cell => cell.trim())
    )
    .filter(cells => cells.length >= 2 && /^`[^`]+`$/.test(cells[0]))
    .map(([name, purpose]) => ({ name: name.slice(1, -1), purpose }))
}

/** One entry per tool name, first mention winning, so a table repeated across references
 *  does not render the same tool twice. */
const uniqueByName = tools => [...new Map(tools.map(tool => [tool.name, tool])).values()]

/** Parses the YAML frontmatter of a SKILL.md. Only flat `key: value` pairs are used, with
 *  wrapped continuation lines folded into the previous value. */
const parseFrontmatter = (text, path) => {
  const lines = text.split('\n')
  if (lines[0]?.trim() !== '---') {
    throw new Error(`${path}: no frontmatter block`)
  }
  const end = lines.findIndex((line, index) => index > 0 && line.trim() === '---')
  if (end === -1) {
    throw new Error(`${path}: frontmatter block is not closed`)
  }

  return lines.slice(1, end).reduce((fields, line) => {
    const match = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/)
    if (match) {
      const [, key, raw] = match
      // `description: >` and `description: |` carry the text on the lines below, so the
      // indicator itself is not the value. Both fold to one line here — a card shows the
      // description as a single paragraph either way.
      const value = /^[|>][+-]?\d*$/.test(raw.trim()) ? '' : raw.replace(/^["']|["']$/g, '').trim()
      return { ...fields, [key]: value, _last: key }
    }
    const continued = line.trim()
    if (!continued || !fields._last) return fields
    return { ...fields, [fields._last]: `${fields[fields._last]} ${continued}`.trim() }
  }, {})
}

/** Everything the skill ships besides SKILL.md, at any depth: references/*.md for most,
 *  a library file at the skill root for others. */
const countBundled = async dir => {
  const entries = await readdir(dir, { withFileTypes: true })
  const counts = await Promise.all(
    entries.map(entry => {
      const path = join(dir, entry.name)
      if (entry.isDirectory()) return countBundled(path)
      return Promise.resolve(entry.name === 'SKILL.md' ? 0 : 1)
    })
  )
  return counts.reduce((total, count) => total + count, 0)
}

const readSkill = async (pluginDir, name) => {
  const dir = join(pluginDir, 'skills', name)
  const path = join(dir, 'SKILL.md')
  const fields = parseFrontmatter(await readFile(path, 'utf8'), path)

  if (fields.name !== name) {
    throw new Error(`${path}: frontmatter name '${fields.name}' != directory name '${name}'`)
  }
  if (!fields.description) {
    throw new Error(`${path}: frontmatter has no description`)
  }

  return {
    name,
    description: fields.description,
    bundled: await countBundled(dir),
    // Not every skill has one, and a card must not link to a directory that is not there.
    hasReferences: existsSync(join(dir, 'references'))
  }
}

const readPlugin = async entry => {
  const source = entry.source.replace(/^\.\//, '').replace(/\/$/, '')
  const dir = join(ROOT, source)
  const manifest = await readJson(join(dir, '.claude-plugin', 'plugin.json'))

  const skillsDir = join(dir, 'skills')
  const names = existsSync(skillsDir) ? await listDirs(skillsDir) : []
  const skills = await Promise.all(names.map(name => readSkill(dir, name)))

  // Every markdown file the plugin ships, so a tool table is found wherever its skill keeps
  // it — in SKILL.md or in any reference below it.
  const markdown = existsSync(skillsDir)
    ? (await listFiles(skillsDir)).filter(path => path.endsWith('.md'))
    : []
  const documents = await Promise.all(markdown.map(path => readFile(path, 'utf8')))

  const mcpPath = join(dir, '.mcp.json')
  const declaredServers = existsSync(mcpPath) ? (await readJson(mcpPath)).mcpServers ?? {} : {}
  const servers = Object.entries(declaredServers).map(([name, config]) => {
    const credential = manifest.userConfig?.[userConfigReference(config.headers)]
    return {
      ...config,
      name,
      credentialTitle: credential?.title,
      credentialNote: credential?.description,
      tools: uniqueByName(documents.flatMap(text => parseToolTable(text, name)))
    }
  })

  return {
    name: manifest.name,
    display: manifest.displayName ?? entry.displayName ?? manifest.name,
    description: manifest.description ?? entry.description ?? '',
    version: manifest.version,
    source,
    servers,
    skills
  }
}

const serverList = servers => servers.map(({ name }) => `<code>${escape(name)}</code>`).join(', ')

const TRANSPORTS = { http: 'HTTP / streamable HTTP', sse: 'Server-sent events', stdio: 'stdio' }

const mcpSummary = servers =>
  servers.length === 0
    ? 'None — this plugin needs no credential'
    : `${serverList(servers)} — automatic in Claude Code`

/* ── page fragments ──────────────────────────────────────────────────────────────── */

const pluginCard = (plugin, root) => `
        <a class="plugin-card" href="${root}${escape(plugin.name)}/">
          <div class="plugin-card-main">
            <header class="plugin-card-head">
              <h3>${escape(plugin.display)}</h3>
              <code>${escape(plugin.name)}</code>
              <span class="plugin-card-ver">v${escape(plugin.version)}</span>
            </header>
            <p class="plugin-card-desc">${escape(plugin.description)}</p>
          </div>
          <div class="plugin-card-side">
            <ul class="plugin-card-skills">
${plugin.skills.map(skill => `              <li>${escape(skill.name)}</li>`).join('\n')}
            </ul>
            <p class="plugin-card-foot">
              <span>${plural(plugin.skills.length, 'skill')}</span>
              <span>${plugin.servers.length === 0 ? 'no credential' : `${escape(plugin.servers.map(server => server.name).join(', '))} MCP`}</span>
              <span class="plugin-card-go">Open<span aria-hidden="true"> →</span></span>
            </p>
          </div>
        </a>`

const skillCard = (skill, plugin, repoUrl) => {
  const path = `${plugin.source}/skills/${escape(skill.name)}`
  const browse = skill.hasReferences
    ? `<a href="${repoUrl}/tree/main/${path}/references">Browse references →</a>`
    : skill.bundled > 0
      ? `<a href="${repoUrl}/tree/main/${path}">Browse the folder →</a>`
      : ''

  return `
        <article class="skill">
          <header class="skill-head">
            <h3 class="skill-name">${escape(skill.name)}</h3>
            <span class="skill-plugin">${escape(plugin.name)}:${escape(skill.name)}</span>
          </header>
          <div class="fm">
            <span class="fm-row"><span class="fm-key">name:</span> <span class="fm-val">${escape(skill.name)}</span></span>
            <span class="fm-row"><span class="fm-key">description:</span> <span class="fm-val">${escape(skill.description)}</span></span>
          </div>
          <dl class="skill-meta">
${skill.bundled > 0 ? `            <div><dt>Bundled files</dt><dd>${skill.bundled}</dd></div>\n` : ''}            <div><dt>Requires</dt><dd>${plugin.servers.length === 0 ? 'No credential' : `${serverList(plugin.servers)} MCP`}</dd></div>
          </dl>
          <p class="skill-links">
            <a href="${repoUrl}/blob/main/${path}/SKILL.md">Read SKILL.md →</a>
            ${browse}
          </p>
        </article>`
}

/** A tool the MCP page documents. Name and purpose come from the skill's own tool table, so
 *  the page describes the tools the skills actually call. */
const toolCard = tool => `
        <article class="skill">
          <header class="skill-head">
            <h3 class="skill-name">${escape(tool.name)}</h3>
          </header>
          <p class="channel-body">${escape(tool.purpose)}</p>
        </article>`

/** A skill that needs the server, marked from the same plugin-level fact the plugin page's
 *  "Requires" row reads: the skill's plugin declares this server. */
const mcpSkillCard = ({ skill, plugin }, root) => `
        <article class="skill">
          <header class="skill-head">
            <h3 class="skill-name">${escape(skill.name)}</h3>
            <span class="skill-plugin">${escape(plugin.name)}:${escape(skill.name)}</span>
          </header>
          <p class="channel-body">${escape(skill.description)}</p>
          <p class="skill-links">
            <a href="${root}${escape(plugin.name)}/">Open ${escape(plugin.display)} →</a>
          </p>
        </article>`

/* ── machine-readable indexes ────────────────────────────────────────────────────── */

/** sitemaps.org 0.9, <loc> only. Google ignores <priority> and <changefreq>, and reads
 *  <lastmod> only where it is consistently accurate — nothing here knows when a page last
 *  changed in a way a reader would care about, so no date is claimed. */
const sitemapXml = urls =>
  '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
  urls.map(url => `  <url>\n    <loc>${escape(url)}</loc>\n  </url>\n`).join('') +
  '</urlset>\n'

/** llmstxt.org: an H1, a blockquote summary, then one H2 section per plugin listing that
 *  plugin's page and each of its skills. Every value is read from the catalog, a
 *  plugin.json, or a SKILL.md frontmatter — nothing here is written by hand. */
const llmsTxt = ({ catalog, plugins, mcpPage, siteUrl, repoUrl }) => {
  const sections = plugins.map(plugin => {
    const rows = [
      `- [${plugin.name}@${catalog.name}](${siteUrl}${plugin.name}/): ${shortNote(plugin.description)}`,
      ...plugin.skills.map(
        skill =>
          `- [${skill.name}](${repoUrl}/blob/main/${plugin.source}/skills/${skill.name}/SKILL.md): ` +
          shortNote(skill.description)
      )
    ]
    return `## ${plugin.display}\n\n${rows.join('\n')}\n`
  })

  const mcpSection =
    `## ${mcpPage.label}\n\n` +
    `- [${mcpPage.label}](${mcpPage.url}): ${shortNote(mcpPage.description)}\n`

  return (
    `# ${catalog.name}\n\n> ${catalog.description}\n\n` + `${sections.join('\n')}\n${mcpSection}`
  )
}

/** A sub-page's visible breadcrumb, in schema.org form: the same two labels and the same
 *  destination, so the markup stays a true representation of what the page shows. The last
 *  item is the page itself and so carries no `item` URL. */
const breadcrumbJsonLd = (catalog, pageLabel, siteUrl) =>
  JSON.stringify(
    {
      '@context': 'https://schema.org',
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: catalog.name, item: siteUrl },
        { '@type': 'ListItem', position: 2, name: pageLabel }
      ]
    },
    null,
    2
    // Inside a <script> element an entity is not decoded, so only `<` needs neutralising.
  ).replaceAll('<', '\\u003c')

/* ── rendering ───────────────────────────────────────────────────────────────────── */

const loadPartials = async () => {
  const files = (await readdir(PARTIALS)).filter(file => file.endsWith('.html'))
  const entries = await Promise.all(
    files.map(async file => [basename(file, '.html'), await readFile(join(PARTIALS, file), 'utf8')])
  )
  return Object.fromEntries(entries)
}

const render = (template, partials, tokens, label) => {
  const withPartials = template.replace(/\{\{>([a-z-]+)\}\}/g, (match, name) => {
    if (!(name in partials)) {
      throw new Error(`${label}: no partial named '${name}' in site/partials/`)
    }
    return partials[name]
  })

  // A function replacement, because a string one would read $&, $', $` and $$ inside the
  // value as substitution patterns — and escape() puts a & in front of every quote.
  const html = Object.entries(tokens).reduce(
    (page, [token, value]) => page.replaceAll(`{{${token}}}`, () => value),
    withPartials
  )

  const unresolved = html.match(/\{\{[A-Z_]+\}\}/g)
  if (unresolved) {
    throw new Error(`${label}: token(s) with no value: ${[...new Set(unresolved)].join(', ')}`)
  }
  return html
}

/** `relativePath` is POSIX-style, because it addresses a URL as much as a file. */
const writeOutput = async (relativePath, contents) => {
  const path = join(OUT, ...relativePath.split('/'))
  await mkdir(dirname(path), { recursive: true })
  await writeFile(path, contents)
}

/** Writes one page and returns its absolute URL. sitemap.xml is built from what these
 *  return, so it lists exactly the pages this build wrote. */
const writePage = async (relativePath, html, siteUrl) => {
  await writeOutput(relativePath, html)
  return `${siteUrl}${relativePath.replace(/(^|\/)index\.html$/, '$1')}`
}

/** Refuses any path containing the repository. `relative`, unlike an OUT + separator
 *  prefix, also handles the filesystem root without turning `/` into `//`. */
const assertOutputOutsideRepository = () => {
  const rootFromOutput = relative(OUT, ROOT)
  const outputContainsRoot =
    rootFromOutput === '' ||
    (rootFromOutput !== '..' && !rootFromOutput.startsWith(`..${sep}`) && !isAbsolute(rootFromOutput))

  if (outputContainsRoot) {
    throw new Error(`refusing to empty ${OUT}: it contains the repository`)
  }
}

/** Removes an empty directory or an output carrying this generator's exact ownership
 *  marker. An index.html is not proof of ownership: it may be somebody else's site. */
const cleanOutputDir = async () => {
  assertOutputOutsideRepository()
  if (!existsSync(OUT)) return false

  const entries = await readdir(OUT)
  if (entries.length > 0) {
    let marker = ''
    try {
      marker = await readFile(join(OUT, BUILD_MARKER), 'utf8')
    } catch {
      // The single refusal below gives the caller the path and recovery action.
    }
    if (marker !== BUILD_MARKER_CONTENT) {
      throw new Error(
        `refusing to empty ${OUT}: it holds files that are not a previous build ` +
          `(missing or invalid ${BUILD_MARKER}). Pass an empty directory, or delete it yourself.`
      )
    }
  }

  await rm(OUT, { recursive: true, force: true })
  return true
}

/** Empties only a marked previous build so deleted plugins and skills leave no stale page. */
const resetOutputDir = async () => {
  await cleanOutputDir()
  await mkdir(OUT, { recursive: true })
  await writeFile(join(OUT, BUILD_MARKER), BUILD_MARKER_CONTENT)
}

/** Every file in site/ that is not one of the templates below is copied out as it is. */
const TEMPLATES = new Set(['template.html', 'plugin.html', 'mcp.html'])

const copyAssets = async () => {
  const assets = (await readdir(SITE, { withFileTypes: true }))
    .filter(entry => entry.isFile() && !TEMPLATES.has(entry.name))
    .map(entry => entry.name)
  await Promise.all(assets.map(file => copyFile(join(SITE, file), join(OUT, file))))
  return assets
}

const build = async () => {
  const catalog = await readJson(join(ROOT, '.claude-plugin', 'marketplace.json'))
  const entries = catalog.plugins.filter(entry => typeof entry.source === 'string')
  if (entries.length === 0) {
    throw new Error('the catalog lists no plugin with a local source path')
  }

  const plugins = await Promise.all(entries.map(readPlugin))
  const skillCount = plugins.reduce((total, plugin) => total + plugin.skills.length, 0)
  if (skillCount === 0) {
    throw new Error('no SKILL.md found under any catalogued plugin')
  }

  // A plugin page renders to /<plugin>/ and the MCP page to /<MCP_PAGE_DIR>/, so one name
  // addresses both. Refuse rather than let whichever is written second win silently.
  const collision = plugins.find(plugin => plugin.name === MCP_PAGE_DIR)
  if (collision) {
    throw new Error(
      `plugin '${collision.name}' would render to ${MCP_PAGE_DIR}/, where the MCP page is ` +
        'written. Rename the plugin, or move the MCP page by changing MCP_PAGE_DIR.'
    )
  }

  // Whichever plugin owns an MCP server is the one the MCP section documents. A plugin
  // that owns none needs no setup, so it is never the subject there.
  const mcpOwner = plugins.find(plugin => plugin.servers.length > 0) ?? plugins[0]
  const mcpServer = mcpOwner.servers[0]

  // Skills that need the server, taken from the same fact the plugin pages' "Requires" row
  // reads — the skill's plugin declares it — rather than from a list written by hand.
  const mcpSkills = plugins.flatMap(plugin =>
    plugin.servers.some(server => server.name === mcpServer?.name)
      ? plugin.skills.map(skill => ({ skill, plugin }))
      : []
  )

  const repoUrl = (entries[0].repository ?? `${catalog.owner.url}/${catalog.name}`).replace(/\.git$/, '')
  const [owner, repo] = repoUrl.split('/').slice(-2)
  const siteUrl = `https://${owner.toLowerCase()}.github.io/${repo}/`
  const catalogSentence = escape(catalog.description.replace(/\.?$/, '.'))

  // Tokens every page shares. Page-specific ones are merged in below.
  const common = {
    CATALOG_NAME: escape(catalog.name),
    SITE_URL: siteUrl,
    CATALOG_DESCRIPTION: escape(catalog.description),
    REPO_URL: repoUrl,
    REPO_SLUG: `${owner}/${repo}`,
    REPO_NAME: repo,
    INSTALL_URL: `https://raw.githubusercontent.com/${owner}/${repo}/main/install.sh`,
    PLUGIN_VERSIONS: plugins
      .map(plugin => `${escape(plugin.name)} v${escape(plugin.version)}`)
      .join(' · ')
  }

  // Everything the MCP server declares about itself, shared by the catalog page's setup
  // section and by the page devoted to the server, so the two cannot describe it differently.
  const mcpTokens = {
    MCP_PAGE_PATH: MCP_PAGE_DIR,
    MCP_PLUGIN: escape(mcpOwner.name),
    MCP_SOURCE: escape(mcpOwner.source),
    MCP_SERVER: escape(mcpServer?.name ?? ''),
    MCP_URL: escape(mcpServer?.url ?? ''),
    MCP_HEADER: escape(Object.keys(mcpServer?.headers ?? {})[0] ?? ''),
    MCP_TRANSPORT: escape(mcpServer?.type ?? ''),
    MCP_TRANSPORT_LABEL: escape(TRANSPORTS[mcpServer?.type] ?? mcpServer?.type ?? ''),
    MCP_CREDENTIAL_TITLE: escape(mcpServer?.credentialTitle ?? 'MCP credential')
  }

  await resetOutputDir()

  const partials = await loadPartials()

  const indexHtml = render(
    await readFile(join(SITE, 'template.html'), 'utf8'),
    partials,
    {
      ...common,
      ...mcpTokens,
      ROOT: './',
      PAGE_TITLE: `${escape(catalog.name)} — ${SITE_IDENTITY}`,
      PAGE_DESCRIPTION: `${catalogSentence} Install the skills into Claude Code, the skills CLI, or any agent that reads SKILL.md.`,
      PAGE_URL: siteUrl,
      CATALOG_SENTENCE: catalogSentence,
      PLUGIN_COUNT_PHRASE: plural(plugins.length, 'plugin'),
      SKILL_COUNT_PHRASE: plural(skillCount, 'skill'),
      PLUGIN_INSTALL_LINES: plugins
        .map(plugin => `/plugin install ${escape(plugin.name)}@${escape(catalog.name)}`)
        .join('\n'),
      PLUGIN_CARDS: plugins.map(plugin => pluginCard(plugin, './')).join('\n')
    },
    'site/template.html'
  )
  const indexUrl = await writePage('index.html', indexHtml, siteUrl)

  const pluginTemplate = await readFile(join(SITE, 'plugin.html'), 'utf8')
  const pluginUrls = await Promise.all(
    plugins.map(plugin => {
      const html = render(
        pluginTemplate,
        partials,
        {
          ...common,
          ROOT: '../',
          // The plugin's own name, then what the site is. `<plugin> — <catalog>` spent the
          // strongest title signal a result has on a name the reader cannot place yet.
          PAGE_TITLE: `${escape(plugin.display)} — ${SITE_IDENTITY}`,
          PAGE_DESCRIPTION: escape(plugin.description.replace(/\.?$/, '.')),
          PAGE_URL: `${siteUrl}${plugin.name}/`,
          PLUGIN_NAME: escape(plugin.name),
          PLUGIN_DISPLAY: escape(plugin.display),
          PLUGIN_DESCRIPTION: escape(plugin.description),
          PLUGIN_VERSION: escape(plugin.version),
          PLUGIN_REF: `${escape(plugin.name)}@${escape(catalog.name)}`,
          PLUGIN_SOURCE: escape(plugin.source),
          PLUGIN_SKILL_COUNT_PHRASE: plural(plugin.skills.length, 'skill'),
          PLUGIN_MCP_SUMMARY: mcpSummary(plugin.servers),
          SKILL_CARDS: plugin.skills.map(skill => skillCard(skill, plugin, repoUrl)).join('\n'),
          BREADCRUMB_JSONLD: breadcrumbJsonLd(catalog, plugin.display, siteUrl)
        },
        `site/plugin.html (${plugin.name})`
      )
      return writePage(`${plugin.name}/index.html`, html, siteUrl)
    })
  )

  // The server's own page. Its tools come from the table the owning plugin's skills keep;
  // with none found the page would claim capabilities it cannot name, so the build stops.
  if (mcpServer && mcpServer.tools.length === 0) {
    throw new Error(
      `no tool table for '${mcpServer.name}' under ${mcpOwner.source}/skills/. ` +
        `Expected a '## MCP Tool: ${mcpServer.name}' heading followed by a | Tool | Purpose | table.`
    )
  }

  const mcpLabel = `${mcpServer?.name ?? ''} MCP`
  const mcpDescription =
    `${mcpServer?.name} is the MCP server MSU builder skills call for MapleStory Universe ` +
    'resources — name search, then sprite, map, skill, and item data from the MSU Open API.'

  const mcpHtml = render(
    await readFile(join(SITE, 'mcp.html'), 'utf8'),
    partials,
    {
      ...common,
      ...mcpTokens,
      ROOT: '../',
      PAGE_TITLE: escape(`${mcpLabel} — ${MCP_PAGE_IDENTITY}`),
      PAGE_DESCRIPTION: escape(mcpDescription),
      PAGE_URL: `${siteUrl}${MCP_PAGE_DIR}/`,
      MCP_PAGE_LABEL: escape(mcpLabel),
      MCP_PAGE_IDENTITY: escape(MCP_PAGE_IDENTITY),
      MCP_CREDENTIAL_NOTE: escape(mcpServer?.credentialNote ?? ''),
      MCP_TOOL_COUNT_PHRASE: plural(mcpServer?.tools.length ?? 0, 'tool'),
      MCP_TOOL_CARDS: (mcpServer?.tools ?? []).map(toolCard).join('\n'),
      MCP_SKILL_COUNT_PHRASE: plural(mcpSkills.length, 'skill'),
      MCP_SKILL_CARDS: mcpSkills.map(entry => mcpSkillCard(entry, '../')).join('\n'),
      BREADCRUMB_JSONLD: breadcrumbJsonLd(catalog, mcpLabel, siteUrl)
    },
    'site/mcp.html'
  )
  const mcpUrl = await writePage(`${MCP_PAGE_DIR}/index.html`, mcpHtml, siteUrl)

  const pageUrls = [indexUrl, ...pluginUrls, mcpUrl]
  await writeOutput('sitemap.xml', sitemapXml(pageUrls))
  await writeOutput(
    'llms.txt',
    llmsTxt({
      catalog,
      plugins,
      mcpPage: { label: mcpLabel, url: mcpUrl, description: mcpDescription },
      siteUrl,
      repoUrl
    })
  )

  const assets = await copyAssets()

  process.stdout.write(
    `${basename(OUT)}/ — ${pageUrls.length} page(s), ` +
      `${plugins.length} plugin(s), ${skillCount} skill(s), ${assets.length} asset(s), ` +
      'sitemap.xml, llms.txt\n'
  )
}

const run = async () => {
  if (cleanOnly) {
    const removed = await cleanOutputDir()
    process.stdout.write(removed ? `removed ${OUT}\n` : `${OUT} does not exist\n`)
    return
  }
  await build()
}

run().catch(error => {
  process.stderr.write(`build-site: ${error.message}\n`)
  process.exit(1)
})
